export type Category={id:string;name:string;name_ar?:string|null;name_en?:string|null;created_at?:string};
export type Lesson={id:string;course_id:string;title:string;description:string;title_ar?:string|null;title_en?:string|null;description_ar?:string|null;description_en?:string|null;youtube_url:string;sort_order:number;created_at?:string};
export type Course={id:string;title:string;description:string;title_ar?:string|null;title_en?:string|null;description_ar?:string|null;description_en?:string|null;image_url:string|null;category_id:string|null;instructor_name:string;published:boolean;created_at?:string;category?:Category;lessons?:Lesson[]};
export type Profile={id:string;full_name:string|null;phone:string|null;age:number|null;bio:string|null;avatar_url:string|null;profile_setup_completed:boolean;role:'student'|'admin';created_at?:string};
export type UserProgress={completedIds:Set<string>;completedAt:Record<string,string>;lastCompletedAt:string|null};
export type HomeExtraSection={enabled:boolean;title:string;description:string;button_label:string;button_url:string};
export type ComponentStyle={visible:boolean;offset_x:string;offset_y:string;width:string;height:string;scale:string;font_size:string;icon_size:string;gap:string;padding:string;border_radius:string;shadow:string;};
export type ComponentEditor=Record<string, ComponentStyle>;
export type UIControls={container_width:string;header_height:string;section_padding:string;section_gap:string;card_padding:string;button_height:string;icon_size:string;button_icon_size:string;header_logo_size:string;header_gap:string;header_logo_offset_x:string;header_actions_offset_x:string;cards_offset_y:string;category_icon_size:string;footer_padding:string;hero_title_size:string;hero_offset_y:string;hero_description_size:string;button_radius:string;card_radius:string;card_offset_x:string;card_scale:string;category_icon_offset_x:string;category_icon_offset_y:string;category_card_padding:string;nav_gap:string;footer_margin_top:string;announcement_height:string};
export type SiteSettings={brand_name:string;logo_url:string;hero_badge:string;hero_title:string;hero_description:string;primary_cta_label:string;secondary_cta_label:string;featured_title:string;featured_description:string;categories_title:string;categories_description:string;footer_text:string;announcement:string;show_categories:boolean;show_featured:boolean;extra_sections:HomeExtraSection[];public_welcome_title:string;public_welcome_description:string;instructor_name:string;instructor_role:string;instructor_image_url:string;support_title:string;support_phone:string;support_whatsapp:string;support_email:string;support_hours:string;support_retention_human_hours:number;support_retention_ai_hours:number;auth_background_image:string;auth_visual_image:string;auth_logo_light:string;auth_logo_dark:string;font_family:string;light_bg:string;light_surface:string;light_text:string;light_muted:string;light_border:string;light_accent:string;light_accent_soft:string;dark_bg:string;dark_surface:string;dark_text:string;dark_muted:string;dark_border:string;dark_accent:string;dark_accent_soft:string;ui_radius:string;ui_shadow:string;ui_controls:UIControls;custom_css:string;component_editor:ComponentEditor};
export type StudentMonitorRow={user_id:string;full_name:string|null;role:'student'|'admin';created_at:string;completed_lessons:number;last_completed_at:string|null;started_courses:number;completion_percent:number};
export type AdminStudentDetails={user_id:string;email:string|null;full_name:string|null;phone:string|null;age:number|null;bio:string|null;avatar_url:string|null;profile_setup_completed:boolean;role:'student'|'admin';created_at:string;completed_lessons:number;started_courses:number;completion_percent:number;last_completed_at:string|null};

export type ConversationStatus='AI_ACTIVE'|'WAITING_FOR_HUMAN'|'ASSIGNED'|'HUMAN_ACTIVE'|'WAITING_FOR_STUDENT'|'RESOLVED'|'CLOSED'|'RETENTION_PENDING'|'REOPENED';
export type ConversationPriority='CRITICAL'|'HIGH'|'NORMAL'|'LOW';
export type Conversation={id:string;student_id:string;type:'AI_CHAT'|'HUMAN_SUPPORT'|'COURSE_QUESTION'|'TECHNICAL_ISSUE'|'ACCOUNT_HELP'|'GENERAL_INQUIRY';status:ConversationStatus;assigned_admin_id:string|null;course_id:string|null;lesson_id:string|null;current_page:string|null;priority:ConversationPriority;created_at:string;updated_at:string;last_message_at:string|null;last_read_at:string|null;admin_replied_at:string|null;resolved_at:string|null;closed_at:string|null;retention_started_at:string|null;auto_delete_at:string|null;retention_exempt:boolean;ai_summary:string|null;legacy_support_request_id:string|null};
export type ConversationMessage={id:string;conversation_id:string;sender_id:string;sender_role:'student'|'admin'|'ai'|'system';body:string;created_at:string;read_at:string|null};
