import { ArrowLeft, BookOpen, Mail, MessageCircle, Phone, PlayCircle, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { defaultSiteSettings, getCategories, getCourses, getSiteSettings } from '../services/data';
import type { Category, Course, SiteSettings } from '../types';
import { supabase } from '../lib/supabase';
import EditableRegion from '../components/EditableRegion';
import { useI18n, localized } from '../i18n';

export default function Home(){ const {t,locale}=useI18n();
  const[courses,setCourses]=useState<Course[]>([]);
  const[cats,setCats]=useState<Category[]>([]);
  const[loading,setLoading]=useState(true);
  const[error,setError]=useState('');
  const[settings,setSettings]=useState<SiteSettings|null>(null);
  const[authenticated,setAuthenticated]=useState(false);
  useEffect(()=>{let active=true;async function load(){try{const site=await getSiteSettings();if(!active)return;setSettings(site);const {data}=await supabase?.auth.getUser() ?? {data:{user:null}};setAuthenticated(!!data.user);if(data.user){const [c,k]=await Promise.all([getCourses(),getCategories()]);if(!active)return;setCourses(c);setCats(k);}}catch(e){if(active)setError(e instanceof Error?e.message:t('home.loadFailed'))}finally{if(active)setLoading(false)}}load();return()=>{active=false}},[]);
  const s = settings || defaultSiteSettings;
  if(loading) return <main className="section"><div className="container"><div className="surface loading-state">جاري تحميل المنصة...</div></div></main>;
  if(error) return <main className="section"><div className="container"><div className="surface empty"><span className="tag">تعذر التحميل</span><h1 className="section-title">مش قادرين نحمل محتوى المنصة</h1><p className="muted">{error}</p><button className="btn btn-primary" onClick={()=>window.location.reload()}>إعادة المحاولة</button></div></div></main>;
  const guest = !authenticated;
  return <>
    {s?.announcement && <div className="announcement"><div className="container">{s.announcement}</div></div>}
    <EditableRegion id="home.hero" config={s.component_editor?.['home.hero']}><section className="hero-section"><div className="container" style={{maxWidth:900}}><span className="tag">{s?.hero_badge ?? t('home.free')}</span><h1 className="hero-title">{s?.hero_title ?? t('home.startJourney')}</h1><p className="muted hero-description">{s?.hero_description ?? t('home.startDesc')}</p><div className="rtl-row" style={{marginTop:26}}><Link className="btn btn-primary" to={guest?'/login':'/courses'}>{guest?t('nav.login'):(s?.primary_cta_label ?? t('home.explore'))} <ArrowLeft size={18}/></Link><Link className="btn btn-ghost" to={guest?'/signup':'/categories'}>{guest?t('home.signup'):(s?.secondary_cta_label ?? t('home.browseCategories'))}</Link></div></div></section></EditableRegion>
    {guest && <section className="section public-guest-section"><div className="container public-guest-grid"><div className="surface public-guest-card"><span className="tag">{t('home.guestTag')}</span><h2>{t('home.guestTitle')}</h2><p className="muted">{t('home.guestDesc')}</p><div className="rtl-row"><Link className="btn btn-primary" to="/login">{t('nav.login')}</Link><Link className="btn btn-ghost" to="/signup">{t('home.signup')}</Link></div></div><div className="surface public-support-card"><div className="public-support-icon"><MessageCircle size={20}/></div><h3>{s.support_title || t('home.customerService')}</h3><p className="muted">{s.support_hours}</p>{s.support_phone&&<a href={`tel:${s.support_phone}`}><Phone size={16}/>{s.support_phone}</a>}{s.support_whatsapp&&<a href={`https://wa.me/${s.support_whatsapp.replace(/\D/g,'')}`} target="_blank" rel="noreferrer"><MessageCircle size={16}/>واتساب</a>}{s.support_email&&<a href={`mailto:${s.support_email}`}><Mail size={16}/>{s.support_email}</a>}{!s.support_phone&&!s.support_whatsapp&&!s.support_email&&<span className="small muted">بيانات الدعم يضيفها صاحب المنصة من لوحة الإدارة.</span>}</div></div></section>}
    {!guest && s?.show_categories !== false && <EditableRegion id="home.categories" config={s.component_editor?.['home.categories']}><section className="section"><div className="container"><div className="section-head"><div><h2 className="section-title">{s?.categories_title ?? t('home.categories')}</h2><div className="muted">{s?.categories_description ?? t('home.categoriesDesc')}</div></div></div><div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))'}}>{cats.slice(0,6).map(c=><Link key={c.id} to={'/courses?category='+c.id} className="surface category-card"><BookOpen size={20}/><strong>{localized(c.name,c.name_ar,c.name_en,locale)}</strong></Link>)}</div></div></section></EditableRegion>}
    {!guest && s?.show_featured !== false && <EditableRegion id="home.featured" config={s.component_editor?.['home.featured']}><section className="section" style={{paddingTop:0}}><div className="container"><div className="section-head"><div><h2 className="section-title">{s?.featured_title ?? t('home.featured')}</h2><div className="muted">{s?.featured_description ?? t('home.featuredDesc')}</div></div><Link to="/courses" className="btn btn-ghost">{t('home.allCourses')}</Link></div>{courses.length?<div className="grid course-grid">{courses.slice(0,3).map(c=><CourseCard key={c.id} course={c}/>)}</div>:<div className="surface empty">{t('home.noCourses')}</div>}</div></section></EditableRegion>}
    {(s?.extra_sections ?? []).filter(x=>x.enabled && x.title.trim()).map((x,i)=><section className="section" style={{paddingTop:i===0?0:12}} key={`${x.title}-${i}`}><div className="container"><div className="surface custom-home-section"><div className="custom-home-icon"><Sparkles size={20}/></div><div><h2 className="section-title">{x.title}</h2>{x.description&&<p className="muted" style={{lineHeight:1.9,maxWidth:750}}>{x.description}</p>}{x.button_label&&x.button_url&&<a className="btn btn-primary" href={x.button_url}>{x.button_label} <ArrowLeft size={17}/></a>}</div></div></div></section>)}
  </>
}
function CourseCard({course}:{course:Course}){ const {t,locale}=useI18n(); return <article className="card"><div className="cover">{course.image_url?<img loading="lazy" decoding="async" src={course.image_url} alt={course.title}/>:<span>EO</span>}</div><div className="card-body"><span className="tag">{course.category?localized(course.category.name,course.category.name_ar,course.category.name_en,locale):t('common.education')}</span><h3 style={{margin:'12px 0 8px',fontSize:20}}>{localized(course.title,course.title_ar,course.title_en,locale)}</h3><p className="muted" style={{lineHeight:1.8,minHeight:58}}>{localized(course.description,course.description_ar,course.description_en,locale)}</p><div className="rtl-row" style={{justifyContent:'space-between',marginTop:18}}><span className="muted" style={{fontSize:13}}>{t('home.lessonsCount',{count:course.lessons?.length??0})}</span><Link className="btn btn-primary" to={'/courses/'+course.id}>{t('common.details')} <PlayCircle size={16}/></Link></div></div></article>}
