import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

type Locale='ar'|'en';
const translations: Record<Locale, Record<string,string>> = {
  ar: {
    'nav.courses':'الكورسات','nav.categories':'التصنيفات','nav.admin':'الإدارة','nav.account':'حسابي','nav.login':'تسجيل الدخول','nav.light':'المظهر الفاتح','nav.dark':'المظهر الداكن','nav.openMenu':'فتح القائمة','nav.closeMenu':'إغلاق القائمة','nav.language':'اللغة',
    'common.loading':'جاري التحميل...','common.retry':'إعادة المحاولة','common.back':'العودة','common.details':'التفاصيل','common.lessons':'الدروس','common.lesson':'درس','common.education':'تعليم','common.noData':'لا توجد بيانات حاليًا.','common.save':'حفظ','common.saving':'جاري الحفظ...','common.cancel':'إلغاء','common.delete':'حذف','common.add':'إضافة','common.search':'البحث','common.allCategories':'كل التصنيفات','common.newest':'الأحدث','common.name':'الاسم','common.lessonCount':'عدد الدروس',
    'home.loading':'جاري تحميل المنصة...','home.loadFailed':'تعذر التحميل','home.loadFailedTitle':'مش قادرين نحمل محتوى المنصة','home.guestTag':'محتوى خاص بالطلاب','home.guestTitle':'الكورسات والدروس متاحة بعد تسجيل الدخول','home.guestDesc':'احفظ تقدمك، افتح الدروس، وتابع رحلتك التعليمية من حسابك. الزائر لن يرى أسماء الكورسات أو محتوى الدروس.','home.free':'منصة تعليمية مجانية','home.explore':'استكشف الكورسات','home.signup':'إنشاء حساب مجاني','home.browseCategories':'تصفح التصنيفات','home.customerService':'خدمة العملاء','home.supportData':'بيانات الدعم يضيفها صاحب المنصة من لوحة الإدارة.','home.whatsapp':'واتساب','home.categories':'التصنيفات','home.categoriesDesc':'اختر المجال الذي تريد تطويره.','home.featured':'أحدث الكورسات','home.featuredDesc':'محتوى مرتب لتبدأ مباشرة.','home.allCourses':'كل الكورسات','home.noCourses':'لا توجد كورسات منشورة بعد.','home.startJourney':'اتعلم مهارات جديدة بخطوات واضحة.','home.startDesc':'كورسات مرتبة، دروس عملية، وتجربة تعلم هادئة تساعدك تبدأ وتكمل بدون تعقيد.','home.categoryExplore':'استكشف الكورسات','home.lessonsCount':'{count} درس',
    'courses.tag':'تعلم بخطوات واضحة','courses.title':'الكورسات','courses.desc':'ابحث، فلتر، ورتّب المحتوى وابدأ التعلم.','courses.searchPlaceholder':'ابحث عن كورس...','courses.noResults':'لا توجد نتائج','courses.noMatch':'مفيش كورسات مطابقة للبحث','courses.tryAgain':'جرّب كلمة مختلفة أو امسح الفلاتر.','courses.showAll':'عرض كل الكورسات','courses.result':'{count} كورس',
    'categories.tag':'مجالات تعليمية','categories.title':'التصنيفات','categories.desc':'اختر المجال الذي تريد تطويره.','categories.noData':'لا توجد تصنيفات متاحة حاليًا.','categories.explore':'استكشف الكورسات ←',
    'course.loading':'جاري تحميل الكورس...','course.notFound':'الكورس غير موجود.','course.instructor':'المدرب: {name}','course.progress':'تقدمك في الكورس','course.continue':'متابعة التعلم','course.start':'ابدأ التعلم','course.curriculum':'المنهج','course.content':'محتوى الكورس','course.completed':'{done} من {total} درس مكتمل','course.complete':'مكتمل','course.comingSoon':'سيتم إضافة الدروس قريبًا.',
    'lesson.loading':'جاري تحميل الدرس أو الدرس غير موجود.','lesson.back':'العودة للكورس','lesson.invalidVideo':'رابط YouTube غير صالح.','lesson.completed':'تم إكمال الدرس','lesson.save':'جاري الحفظ...','lesson.markComplete':'تحديد كدرس مكتمل','lesson.previous':'السابق','lesson.next':'التالي','lesson.watching':'تشاهده الآن',
    'assistant.title':'مساعد ENG OSAMA','assistant.online':'مساعد داخل المنصة','assistant.welcome':'أهلًا بيك 👋 أنا مساعد ENG OSAMA. قولّي محتاج إيه وأنا أساعدك.','assistant.support':'التواصل مع الدعم','assistant.supportTitle':'إرسال للدعم','assistant.supportPlaceholder':'اكتب المشكلة بالتفصيل...','assistant.send':'إرسال','assistant.sent':'تم إرسال طلب الدعم بنجاح.','assistant.emptySupport':'اكتب المشكلة أولًا.','assistant.needHelp':'لو سؤالك يحتاج تدخل من فريق الدعم اضغط «إرسال للدعم».','assistant.fallback':'أنا مساعد ENG OSAMA داخل المنصة. أقدر أساعدك في التنقل، الكورسات والدروس، أو تسجيل مشكلة للدعم.','assistant.start':'مش عارف أبدأ منين','assistant.courseIssue':'الكورس مش شغال','assistant.contact':'عايز أكلم الدعم',
    'guard.checking':'جاري التحقق من الصلاحيات...','notFound.title':'الصفحة غير موجودة','notFound.desc':'الرابط الذي فتحته غير متاح.','notFound.home':'العودة للرئيسية',
    'language.ar':'العربية','language.en':'English'
  },
  en: {
    'nav.courses':'Courses','nav.categories':'Categories','nav.admin':'Admin','nav.account':'Account','nav.login':'Sign in','nav.light':'Light mode','nav.dark':'Dark mode','nav.openMenu':'Open menu','nav.closeMenu':'Close menu','nav.language':'Language',
    'common.loading':'Loading...','common.retry':'Try again','common.back':'Back','common.details':'Details','common.lessons':'Lessons','common.lesson':'lesson','common.education':'Education','common.noData':'No data available yet.','common.save':'Save','common.saving':'Saving...','common.cancel':'Cancel','common.delete':'Delete','common.add':'Add','common.search':'Search','common.allCategories':'All categories','common.newest':'Newest','common.name':'Name','common.lessonCount':'Lesson count',
    'home.loading':'Loading the platform...','home.loadFailed':'Unable to load','home.loadFailedTitle':'We couldn’t load the platform content','home.guestTag':'Student-only content','home.guestTitle':'Courses and lessons are available after signing in','home.guestDesc':'Save your progress, open lessons, and continue your learning journey from your account. Visitors cannot see course names or lesson content.','home.free':'Free learning platform','home.explore':'Explore courses','home.signup':'Create a free account','home.browseCategories':'Browse categories','home.customerService':'Customer support','home.supportData':'Support details are managed by the platform owner in Admin.','home.whatsapp':'WhatsApp','home.categories':'Categories','home.categoriesDesc':'Choose the area you want to develop.','home.featured':'Latest courses','home.featuredDesc':'Organized content to help you start right away.','home.allCourses':'All courses','home.noCourses':'No published courses yet.','home.startJourney':'Learn new skills with clear steps.','home.startDesc':'Organized courses, practical lessons, and a calm learning experience that helps you start and keep going.','home.categoryExplore':'Explore courses','home.lessonsCount':'{count} lessons',
    'courses.tag':'Learn with clear steps','courses.title':'Courses','courses.desc':'Search, filter, sort, and start learning.','courses.searchPlaceholder':'Search for a course...','courses.noResults':'No results','courses.noMatch':'No courses match your search','courses.tryAgain':'Try another keyword or clear the filters.','courses.showAll':'Show all courses','courses.result':'{count} courses',
    'categories.tag':'Learning areas','categories.title':'Categories','categories.desc':'Choose the area you want to develop.','categories.noData':'No categories are available right now.','categories.explore':'Explore courses →',
    'course.loading':'Loading course...','course.notFound':'Course not found.','course.instructor':'Instructor: {name}','course.progress':'Your course progress','course.continue':'Continue learning','course.start':'Start learning','course.curriculum':'Curriculum','course.content':'Course content','course.completed':'{done} of {total} lessons completed','course.complete':'Completed','course.comingSoon':'Lessons will be added soon.',
    'lesson.loading':'Loading lesson or lesson not found.','lesson.back':'Back to course','lesson.invalidVideo':'Invalid YouTube URL.','lesson.completed':'Lesson completed','lesson.save':'Saving...','lesson.markComplete':'Mark as complete','lesson.previous':'Previous','lesson.next':'Next','lesson.watching':'Watching now',
    'assistant.title':'ENG OSAMA Assistant','assistant.online':'In-platform assistant','assistant.welcome':'Hi 👋 I’m the ENG OSAMA assistant. Tell me what you need and I’ll help.','assistant.support':'Contact support','assistant.supportTitle':'Send to support','assistant.supportPlaceholder':'Describe the problem...','assistant.send':'Send','assistant.sent':'Your support request was sent successfully.','assistant.emptySupport':'Describe the problem first.','assistant.needHelp':'If your question needs the support team, use “Contact support”.','assistant.fallback':'I’m the ENG OSAMA assistant. I can help with navigation, courses and lessons, or record a support issue.','assistant.start':'I don’t know where to start','assistant.courseIssue':'The course is not working','assistant.contact':'I want to contact support',
    'guard.checking':'Checking permissions...','notFound.title':'Page not found','notFound.desc':'The link you opened is not available.','notFound.home':'Back to home',
    'language.ar':'العربية','language.en':'English'
  }
};

const I18nContext=createContext<{locale:Locale; setLocale:(l:Locale)=>void; t:(key:string,vars?:Record<string,string|number>)=>string}>({locale:'ar',setLocale:()=>{},t:(k)=>k});
export function LanguageProvider({children}:{children:ReactNode}){
 const [locale,setLocaleState]=useState<Locale>(()=>{const saved=localStorage.getItem('eng-osama-locale'); return saved==='en'||saved==='ar'?saved:'ar'});
 const setLocale=(l:Locale)=>{setLocaleState(l);localStorage.setItem('eng-osama-locale',l)};
 useEffect(()=>{document.documentElement.lang=locale;document.documentElement.dir=locale==='ar'?'rtl':'ltr';document.body.dir=locale==='ar'?'rtl':'ltr'; document.title=locale==='ar'?'ENG OSAMA — منصة تعليمية مجانية':'ENG OSAMA — Free Learning Platform'; const desc=document.querySelector('meta[name=description]'); if(desc) desc.setAttribute('content',locale==='ar'?'ENG OSAMA — منصة تعليمية مجانية بكورسات ودروس مرتبة وواضحة.':'ENG OSAMA — a free learning platform with organized courses and practical lessons.'); const og=document.querySelector('meta[property=og:description]'); if(og) og.setAttribute('content',locale==='ar'?'اتعلم مهارات جديدة بخطوات واضحة.':'Learn new skills with clear steps.');},[locale]);
 const value=useMemo(()=>({locale,setLocale,t:(key:string,vars?:Record<string,string|number>)=>{let s=translations[locale][key]??translations.ar[key]??key; for(const [k,v] of Object.entries(vars??{}))s=s.replaceAll(`{${k}}`,String(v)); return s}}),[locale]);
 return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>
}
export const useI18n=()=>useContext(I18nContext);
export function localized(base:string|undefined|null, ar:string|undefined|null, en:string|undefined|null, locale:Locale){return (locale==='en'?en:ar) || base || ''}
