import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type Locale = 'ar' | 'en';
const STORAGE_KEY = 'eng-osama-locale';

const translations = {
  ar: {
    'nav.courses':'الكورسات','nav.categories':'التصنيفات','nav.admin':'الإدارة','nav.account':'حسابي','nav.login':'تسجيل الدخول','nav.logout':'تسجيل الخروج','nav.menu.open':'فتح القائمة','nav.menu.close':'إغلاق القائمة','nav.theme.light':'تفعيل المظهر الفاتح','nav.theme.dark':'تفعيل المظهر الداكن','nav.light':'فاتح','nav.dark':'داكن','nav.language':'اللغة',
    'common.loading':'جاري التحميل...','common.retry':'إعادة المحاولة','common.save':'حفظ','common.saving':'جاري الحفظ...','common.cancel':'إلغاء','common.close':'إغلاق','common.back':'رجوع','common.send':'إرسال','common.add':'إضافة','common.edit':'تعديل','common.delete':'حذف','common.open':'فتح','common.details':'التفاصيل','common.next':'التالي','common.previous':'السابق','common.error':'حدث خطأ','common.unexpected':'حدث خطأ غير متوقع.','common.noResults':'لا توجد نتائج','common.noData':'لا يوجد بعد','common.student':'طالب','common.admin':'مدير','common.course':'كورس','common.lesson':'درس',
    'home.badge':'منصة تعليمية مجانية','home.title':'اتعلم مهارات جديدة بخطوات واضحة.','home.description':'كورسات مرتبة، دروس عملية، وتجربة تعلم هادئة تساعدك تبدأ وتكمل بدون تعقيد.','home.explore':'استكشف الكورسات','home.browse':'تصفح التصنيفات','home.latest':'أحدث الكورسات','home.latestDesc':'محتوى مرتب لتبدأ مباشرة.','home.allCourses':'كل الكورسات','home.categories':'التصنيفات','home.categoriesDesc':'اختر المجال الذي تريد تطويره.','home.studentOnly':'محتوى خاص بالطلاب','home.loginRequired':'الكورسات والدروس متاحة بعد تسجيل الدخول','home.loginRequiredDesc':'احفظ تقدمك، افتح الدروس، وتابع رحلتك التعليمية من حسابك. الزائر لن يرى أسماء الكورسات أو محتوى الدروس.','home.customerService':'خدمة العملاء','home.supportFallback':'بيانات الدعم يضيفها صاحب المنصة من لوحة الإدارة.','home.noCourses':'لا توجد كورسات منشورة بعد.','home.freeAccount':'إنشاء حساب مجاني','home.login':'تسجيل الدخول','home.education':'تعليم',
    'courses.badge':'تعلم بخطوات واضحة','courses.title':'الكورسات','courses.description':'ابحث، فلتر، ورتّب المحتوى وابدأ التعلم.','courses.search':'ابحث عن كورس...','courses.category':'التصنيف','courses.allCategories':'كل التصنيفات','courses.sort':'الترتيب','courses.newest':'الأحدث','courses.name':'الاسم','courses.lessons':'عدد الدروس','courses.clear':'مسح الفلاتر','courses.result':'كورس','courses.emptyTitle':'مفيش كورسات مطابقة للبحث','courses.emptyDesc':'جرّب كلمة مختلفة أو امسح الفلاتر.','courses.showAll':'عرض كل الكورسات','courses.retry':'إعادة المحاولة','courses.error':'تعذر تحميل الكورسات.','courses.lessonCount':'درس','courses.details':'التفاصيل',
    'categories.badge':'مجالات تعليمية','categories.title':'التصنيفات','categories.description':'اختر المجال الذي تريد تطويره.','categories.explore':'استكشف الكورسات','categories.error':'تعذر تحميل التصنيفات.','categories.empty':'لا توجد تصنيفات بعد.','categories.noCourses':'لا توجد كورسات في هذا التصنيف بعد.',
    'lesson.back':'العودة للكورس','lesson.curriculum':'المنهج','lesson.lesson':'الدرس','lesson.watchNow':'تشاهده الآن','lesson.complete':'تحديد كدرس مكتمل','lesson.completed':'تم إكمال الدرس','lesson.saving':'جاري الحفظ...','lesson.invalidYoutube':'رابط YouTube غير صالح.','lesson.loading':'جاري تحميل الدرس أو الدرس غير موجود.','lesson.next':'التالي','lesson.previous':'السابق',
    'course.progress':'تقدمك في الكورس','course.instructor':'المدرب','course.curriculum':'المنهج','course.content':'محتوى الكورس','course.start':'ابدأ التعلم','course.continue':'متابعة التعلم','course.completed':'مكتمل','course.education':'تعليم',
    'account.profile':'الملف الشخصي','account.hello':'أهلًا','account.studentAccount':'حساب طالب','account.avatar':'صورة الملف الشخصي','account.changeAvatar':'تغيير صورة الملف الشخصي','account.light':'مظهر فاتح','account.dark':'مظهر داكن','account.started':'الكورسات التي بدأت','account.completedLessons':'الدروس المكتملة','account.completion':'نسبة إكمال المحتوى','account.lastActivity':'آخر نشاط','account.continue':'استكمال التعلم','account.currentCourses':'الكورسات الحالية','account.learningPath':'مساري التعليمي','account.accountData':'بيانات الحساب','account.myInfo':'معلوماتي','account.myInfoDesc':'يمكنك تعديل الاسم، بينما البريد مرتبط بحساب المصادقة.','account.name':'الاسم','account.phone':'رقم الهاتف','account.age':'العمر','account.bio':'نبذة عني','account.bioPlaceholder':'نبذة قصيرة عنك (اختياري)','account.email':'البريد الإلكتروني','account.saveData':'حفظ البيانات','account.security':'الأمان','account.changePassword':'تغيير كلمة المرور','account.newPassword':'كلمة المرور الجديدة','account.confirmPassword':'تأكيد كلمة المرور','account.passwordHint':'استخدم 6 أحرف على الأقل.','account.savePassword':'حفظ كلمة المرور','account.noCourse':'لم تبدأ أي كورس بعد. ابدأ أول رحلة تعليمية الآن.','account.follow':'متابعة','account.completed':'مكتمل','account.next':'التالي','account.noActivity':'لا يوجد بعد','account.logout':'تسجيل الخروج',
    'auth.login':'سجّل دخولك','auth.signup':'أنشئ حسابك','auth.loginDesc':'ادخل إلى حسابك وكمل رحلتك التعليمية.','auth.signupDesc':'أنشئ حسابك أولًا، وبعدها يمكنك إضافة معلوماتك الشخصية أو تخطيها.','auth.name':'الاسم','auth.fullName':'الاسم الكامل','auth.email':'البريد الإلكتروني','auth.password':'كلمة المرور','auth.newPassword':'كلمة المرور الجديدة','auth.confirmPassword':'تأكيد كلمة المرور','auth.forgot':'نسيت كلمة المرور؟','auth.create':'إنشاء الحساب','auth.createAccount':'إنشاء حساب','auth.haveAccount':'لديك حساب؟','auth.noAccount':'ليس لديك حساب؟','auth.reset':'استعادة الحساب','auth.resetTitle':'نسيت كلمة المرور؟','auth.resetDesc':'أدخل بريدك وسنرسل لك رابطًا آمنًا لتعيين كلمة مرور جديدة.','auth.sendReset':'إرسال رابط الاستعادة','auth.backLogin':'العودة لتسجيل الدخول','auth.verify':'تفعيل الحساب','auth.checkEmail':'راجع بريدك الإلكتروني','auth.checkEmailDesc':'أرسلنا رسالة تفعيل إلى البريد التالي. افتح الرسالة واضغط على رابط التأكيد لإكمال إنشاء حسابك.','auth.resend':'إعادة إرسال رسالة التفعيل','auth.setup':'معلوماتك','auth.setupDesc':'خطوة اختيارية','auth.saveContinue':'حفظ والمتابعة','auth.skip':'تخطي هذه الخطوة','auth.uploadAvatar':'إضافة صورة شخصية','auth.passwordShow':'إظهار','auth.passwordHide':'إخفاء','auth.dark':'داكن','auth.light':'فاتح',
    'assistant.title':'مساعد ENG OSAMA','assistant.subtitle':'مساعدة داخل المنصة','assistant.open':'فتح المساعد','assistant.close':'إغلاق المساعد','assistant.send':'إرسال','assistant.message':'رسالتك','assistant.placeholder':'اكتب رسالتك...','assistant.support':'محتاج تتواصل مع الدعم؟','assistant.supportTitle':'إرسال للدعم','assistant.supportPlaceholder':'اكتب المشكلة بالتفصيل...','assistant.back':'رجوع','assistant.sendRequest':'إرسال الطلب','assistant.sending':'جارٍ الإرسال...','assistant.sent':'تم الإرسال.','assistant.help':'أنا مساعد ENG OSAMA داخل المنصة. أقدر أساعدك في التنقل، الكورسات والدروس، أو تسجيل مشكلة للدعم. لو سؤالك يحتاج تدخل من فريق الدعم اضغط «إرسال للدعم».','assistant.welcome':'أهلاً بيك 👋 أنا مساعد ENG OSAMA. قولّي محتاج إيه وأنا أساعدك.','assistant.start':'ابدأ','assistant.course':'كورس','assistant.lesson':'درس','assistant.video':'فيديو','assistant.account':'حساب','assistant.supportShort':'دعم','assistant.problem':'مشكلة','assistant.videoHelp':'لو الدرس أو الفيديو مش شغال، جرّب تحديث الصفحة والتأكد من اتصال الإنترنت. لو المشكلة مستمرة، ابعتلي تفاصيل المشكلة من زر «إرسال للدعم» وأنا أجهز طلب للدعم.','assistant.accountHelp':'لو المشكلة في تسجيل الدخول أو الحساب، استخدم صفحة تسجيل الدخول أو استعادة كلمة المرور. ولو ما اتحلتش، أرسل طلب للدعم وسنراجع المشكلة.','assistant.courseHelp':'تقدر تشوف الكورسات من قسم «الكورسات»، وتفتح أي كورس للوصول إلى الدروس ومتابعة تقدمك.','assistant.startHelp':'ابدأ من صفحة الكورسات، واختار الكورس المناسب لك. حاول تمشي بالترتيب درسًا بعد درس، وكل درس تقدر تعلّمه كمكتمل بعد الانتهاء منه.','assistant.supportIntro':'أكيد. أقدر أسجل لك طلب دعم داخل المنصة، وبعدها فريق الدعم يراجعه. اضغط «إرسال للدعم» واكتب المشكلة بالتفصيل.','assistant.supportSuccess':'تم إرسال طلبك للدعم بنجاح ✅ فريق الدعم سيراجعه.','assistant.supportError':'تعذر إرسال الطلب حاليًا. تأكد من الاتصال وحاول مرة أخرى.',
    'errors.notFound':'الصفحة غير موجودة','errors.notFoundDesc':'الرابط الذي فتحته غير متاح.','errors.refresh':'تحديث الصفحة','errors.permission':'جاري التحقق من الصلاحيات...','errors.generic':'حصلت مشكلة غير متوقعة','errors.genericDesc':'جرّب تحديث الصفحة. لو المشكلة مستمرة، تواصل مع إدارة المنصة.',
    'footer.tagline':'تعلم مجانًا، بخطوات واضحة.'
  },
  en: {
    'nav.courses':'Courses','nav.categories':'Categories','nav.admin':'Admin','nav.account':'My Account','nav.login':'Sign in','nav.logout':'Sign out','nav.menu.open':'Open menu','nav.menu.close':'Close menu','nav.theme.light':'Switch to light mode','nav.theme.dark':'Switch to dark mode','nav.light':'Light','nav.dark':'Dark','nav.language':'Language',
    'common.loading':'Loading...','common.retry':'Try again','common.save':'Save','common.saving':'Saving...','common.cancel':'Cancel','common.close':'Close','common.back':'Back','common.send':'Send','common.add':'Add','common.edit':'Edit','common.delete':'Delete','common.open':'Open','common.details':'Details','common.next':'Next','common.previous':'Previous','common.error':'Error','common.unexpected':'Something went wrong.','common.noResults':'No results','common.noData':'Not available yet','common.student':'Student','common.admin':'Admin','common.course':'Course','common.lesson':'Lesson',
    'home.badge':'Free learning platform','home.title':'Learn new skills, one clear step at a time.','home.description':'Organized courses, practical lessons, and a calm learning experience that helps you start and keep going without the complexity.','home.explore':'Explore courses','home.browse':'Browse categories','home.latest':'Latest courses','home.latestDesc':'Organized content to help you start right away.','home.allCourses':'All courses','home.categories':'Categories','home.categoriesDesc':'Choose the area you want to develop.','home.studentOnly':'Student-only content','home.loginRequired':'Courses and lessons are available after signing in','home.loginRequiredDesc':'Save your progress, open lessons, and continue your learning journey from your account. Visitors cannot see course names or lesson content.','home.customerService':'Customer support','home.supportFallback':'Support details are managed by the platform owner.','home.noCourses':'No published courses yet.','home.freeAccount':'Create a free account','home.login':'Sign in','home.education':'Education',
    'courses.badge':'Learn with clear steps','courses.title':'Courses','courses.description':'Search, filter, sort, and start learning.','courses.search':'Search for a course...','courses.category':'Category','courses.allCategories':'All categories','courses.sort':'Sort by','courses.newest':'Newest','courses.name':'Name','courses.lessons':'Number of lessons','courses.clear':'Clear filters','courses.result':'course','courses.emptyTitle':'No courses match your search','courses.emptyDesc':'Try a different keyword or clear the filters.','courses.showAll':'Show all courses','courses.retry':'Try again','courses.error':'Unable to load courses.','courses.lessonCount':'lessons','courses.details':'Details',
    'categories.badge':'Learning areas','categories.title':'Categories','categories.description':'Choose the area you want to develop.','categories.explore':'Explore courses','categories.error':'Unable to load categories.','categories.empty':'No categories yet.','categories.noCourses':'No courses in this category yet.',
    'lesson.back':'Back to course','lesson.curriculum':'Curriculum','lesson.lesson':'Lesson','lesson.watchNow':'Watching now','lesson.complete':'Mark as complete','lesson.completed':'Lesson completed','lesson.saving':'Saving...','lesson.invalidYoutube':'Invalid YouTube URL.','lesson.loading':'Loading lesson or lesson not found.','lesson.next':'Next','lesson.previous':'Previous',
    'course.progress':'Your course progress','course.instructor':'Instructor','course.curriculum':'Curriculum','course.content':'Course content','course.start':'Start learning','course.continue':'Continue learning','course.completed':'Completed','course.education':'Education',
    'account.profile':'Profile','account.hello':'Hello','account.studentAccount':'Student account','account.avatar':'Profile picture','account.changeAvatar':'Change profile picture','account.light':'Light mode','account.dark':'Dark mode','account.started':'Courses started','account.completedLessons':'Completed lessons','account.completion':'Content completion','account.lastActivity':'Last activity','account.continue':'Continue learning','account.currentCourses':'Current courses','account.learningPath':'My learning path','account.accountData':'Account details','account.myInfo':'My information','account.myInfoDesc':'You can edit your name; your email is linked to authentication.','account.name':'Name','account.phone':'Phone number','account.age':'Age','account.bio':'About me','account.bioPlaceholder':'A short bio (optional)','account.email':'Email','account.saveData':'Save details','account.security':'Security','account.changePassword':'Change password','account.newPassword':'New password','account.confirmPassword':'Confirm password','account.passwordHint':'Use at least 6 characters.','account.savePassword':'Save password','account.noCourse':'You have not started a course yet. Start your first learning journey now.','account.follow':'Continue','account.completed':'Completed','account.next':'Next','account.noActivity':'Not available yet','account.logout':'Sign out',
    'auth.login':'Sign in','auth.signup':'Create your account','auth.loginDesc':'Sign in to your account and continue your learning journey.','auth.signupDesc':'Create your account first, then add your personal information or skip it.','auth.name':'Name','auth.fullName':'Full name','auth.email':'Email','auth.password':'Password','auth.newPassword':'New password','auth.confirmPassword':'Confirm password','auth.forgot':'Forgot your password?','auth.create':'Create account','auth.createAccount':'Create an account','auth.haveAccount':'Already have an account?','auth.noAccount':'Don’t have an account?','auth.reset':'Account recovery','auth.resetTitle':'Forgot your password?','auth.resetDesc':'Enter your email and we’ll send you a secure link to set a new password.','auth.sendReset':'Send reset link','auth.backLogin':'Back to sign in','auth.verify':'Verify account','auth.checkEmail':'Check your email','auth.checkEmailDesc':'We sent an activation email to the address below. Open it and click the confirmation link to finish creating your account.','auth.resend':'Resend activation email','auth.setup':'Your information','auth.setupDesc':'Optional step','auth.saveContinue':'Save & continue','auth.skip':'Skip this step','auth.uploadAvatar':'Add profile picture','auth.passwordShow':'Show','auth.passwordHide':'Hide','auth.dark':'Dark','auth.light':'Light',
    'assistant.title':'ENG OSAMA Assistant','assistant.subtitle':'Help inside the platform','assistant.open':'Open assistant','assistant.close':'Close assistant','assistant.send':'Send','assistant.message':'Your message','assistant.placeholder':'Type your message...','assistant.support':'Need to contact support?','assistant.supportTitle':'Send to support','assistant.supportPlaceholder':'Describe the problem...','assistant.back':'Back','assistant.sendRequest':'Send request','assistant.sending':'Sending...','assistant.sent':'Sent.','assistant.help':'I’m the ENG OSAMA assistant. I can help with navigation, courses, lessons, or support requests. If your question needs a support team member, choose “Send to support”.','assistant.welcome':'Hi 👋 I’m the ENG OSAMA assistant. Tell me what you need and I’ll help.','assistant.start':'Get started','assistant.course':'Course','assistant.lesson':'Lesson','assistant.video':'Video','assistant.account':'Account','assistant.supportShort':'Support','assistant.problem':'Problem','assistant.videoHelp':'If the lesson or video is not working, refresh the page and check your internet connection. If the issue continues, send me the details and I’ll prepare a support request.','assistant.accountHelp':'If the issue is with sign-in or your account, use the sign-in or password recovery page. If it is not resolved, send a support request and we’ll review it.','assistant.courseHelp':'Open the Courses section, choose a course, and access its lessons to follow your progress.','assistant.startHelp':'Start from the Courses page and choose a course. Follow the lessons in order, and mark each lesson complete when you finish it.','assistant.supportIntro':'Sure. I can create a support request inside the platform for the support team to review. Choose “Send to support” and describe the problem.','assistant.supportSuccess':'Your support request was sent successfully ✅ The support team will review it.','assistant.supportError':'The request could not be sent right now. Check your connection and try again.',
    'errors.notFound':'Page not found','errors.notFoundDesc':'The link you opened is not available.','errors.refresh':'Refresh page','errors.permission':'Checking permissions...','errors.generic':'Something went wrong','errors.genericDesc':'Try refreshing the page. If the problem continues, contact platform support.',
    'footer.tagline':'Learn for free, one clear step at a time.'
  }
} as const;

export type TranslationKey = keyof typeof translations.en;
export function t(key: TranslationKey, locale: Locale = getStoredLocale()): string { return translations[locale][key] ?? translations.en[key] ?? key; }
export function getStoredLocale(): Locale { return localStorage.getItem(STORAGE_KEY) === 'en' ? 'en' : 'ar'; }

type Ctx = { locale: Locale; setLocale: (locale: Locale) => void; t: (key: TranslationKey) => string };
const I18nContext = createContext<Ctx | null>(null);
export function I18nProvider({children}:{children:ReactNode}) {
  const [locale,setLocaleState] = useState<Locale>(getStoredLocale);
  const setLocale = (next: Locale) => setLocaleState(next);
  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, locale);
    const root = document.documentElement;
    root.lang = locale === 'ar' ? 'ar-EG' : 'en-GB';
    root.dir = locale === 'ar' ? 'rtl' : 'ltr';
    root.dataset.locale = locale;
    document.title = locale === 'ar' ? 'ENG OSAMA | منصة تعليمية' : 'ENG OSAMA | Learning Platform';
  }, [locale]);
  const value = useMemo(() => ({ locale, setLocale, t: (key: TranslationKey) => t(key, locale) }), [locale]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}
export function useI18n(){ const ctx=useContext(I18nContext); if(!ctx) throw new Error('useI18n must be used inside I18nProvider'); return ctx; }

export function localizeText(locale: Locale, value: string | null | undefined, ar?: string | null, en?: string | null): string {
  if (locale === 'en') return en?.trim() || value || ar?.trim() || '';
  return ar?.trim() || value || en?.trim() || '';
}
